"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class apriltag_msg(object):
    __slots__ = ["timestamp", "distance"]

    def __init__(self):
        self.timestamp = 0
        self.distance = 0

    def encode(self):
        buf = BytesIO()
        buf.write(apriltag_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp, self.distance))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != apriltag_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return apriltag_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = apriltag_msg()
        self.timestamp, self.distance = struct.unpack(">qi", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if apriltag_msg in parents: return 0
        tmphash = (0xb2dcfe0d0408c076) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if apriltag_msg._packed_fingerprint is None:
            apriltag_msg._packed_fingerprint = struct.pack(">Q", apriltag_msg._get_hash_recursive([]))
        return apriltag_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

