"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class message(object):
    __slots__ = ["timestamp", "value", "name"]

    def __init__(self):
        self.timestamp = 0
        self.value = 0
        self.name = ""

    def encode(self):
        buf = BytesIO()
        buf.write(message._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp, self.value))
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != message._get_packed_fingerprint():
            raise ValueError("Decode error")
        return message._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = message()
        self.timestamp, self.value = struct.unpack(">qi", buf.read(12))
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if message in parents: return 0
        tmphash = (0x24346c1d5f4a56d1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if message._packed_fingerprint is None:
            message._packed_fingerprint = struct.pack(">Q", message._get_hash_recursive([]))
        return message._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

