"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class good_mic_msg(object):
    __slots__ = ["timestamp", "VAD", "angle", "dir"]

    __typenames__ = ["int64_t", "int32_t", "int32_t", "int32_t"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        self.VAD = 0
        self.angle = 0
        self.dir = 0

    def encode(self):
        buf = BytesIO()
        buf.write(good_mic_msg._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qiii", self.timestamp, self.VAD, self.angle, self.dir))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != good_mic_msg._get_packed_fingerprint():
            raise ValueError("Decode error")
        return good_mic_msg._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = good_mic_msg()
        self.timestamp, self.VAD, self.angle, self.dir = struct.unpack(">qiii", buf.read(20))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if good_mic_msg in parents: return 0
        tmphash = (0xed51550b1babf4c4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if good_mic_msg._packed_fingerprint is None:
            good_mic_msg._packed_fingerprint = struct.pack(">Q", good_mic_msg._get_hash_recursive([]))
        return good_mic_msg._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", good_mic_msg._get_packed_fingerprint())[0]

