#ifndef PE_PE_CHANNELS_HPP
#define PE_PE_CHANNELS_HPP

#define PE_REQUEST_CHANNEL "PE_WAYPOINT"
#define PE_HEADING_CHANNEL "PE_HEADING"
#define PE_SHUTDOWN_CHANNEL "PE_SHUTDOWN"
#define CAMERA_1_CHANNEL "CAMERA_1_CHANNEL"
#define CAMERA_2_CHANNEL "CAMERA_2_CHANNEL"
#define CAMERA_3_CHANNEL "CAMERA_3_CHANNEL"
#define MICROPHONE_CHANNEL "MICROPHONE_CHANNEL"

#endif // PE_PE_CHANNELS_HPP