#ifndef PE_PE_CHANNELS_HPP
#define PE_PE_CHANNELS_HPP

#define PE_REQUEST_CHANNEL "PE_WAYPOINT"
#define PE_SHUTDOWN_CHANNEL "PE_SHUTDOWN"
#define CAMERA_1_CHANNEL "CAMERA_1_CHANNEL"
#define CAMERA_2_CHANNEL "CAMERA_2_CHANNEL"
#define CAMERA_3_CHANNEL "CAMERA_3_CHANNEL"
#define GOOD_MICROPHONE_CHANNEL "GOOD_MICROPHONE_CHANNEL"
#define BAD_MICROPHONE_CHANNEL "BAD_MICROPHONE_CHANNEL"

#endif // PE_PE_CHANNELS_HPP