#ifndef PE_PE_CHANNELS_HPP
#define PE_PE_CHANNELS_HPP

#define PE_REQUEST_CHANNEL "PE_WAYPOINT"
#define PE_HEADING_CHANNEL "PE_HEADING"
#define PE_SHUTDOWN_CHANNEL "PE_SHUTDOWN"

#endif // PE_PE_CHANNELS_HPP